[package]
name = "panic-contract"
version = "0.1.0"
edition = "2021"
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { version = "25", features = ["testutils"] }

[dev-dependencies]
soroban-cost-harness = { path = "../../../harness", version = "1.0.0" }
soroban-sdk = { version = "25", features = ["testutils"] }
